import { Question, OptionItem } from './types';

const createOptions = (answers: string[]): OptionItem[] => {
  return answers.map((answer, index) => {
    const rank = index + 1;
    const points = (11 - rank) * 10; // 1 -> 100, 2 -> 90 ... 10 -> 10
    return {
      rank,
      points,
      answer,
      revealed: false,
    };
  });
};

export const DEFAULT_ROUND_NAME = 'Jackpot Round';

export const DEFAULT_QUESTIONS: Question[] = [
  {
    id: 1,
    category: 'BOTTLENECK: GLOBAL MARITIME CHOKEPOINTS',
    options: createOptions([
      'Strait of Malacca',
      'Strait of Hormuz',
      'Suez Canal',
      'Bab-el-Mandeb',
      'Panama Canal',
      'Bosporus Strait',
      'Strait of Gibraltar',
      'Danish Straits',
      'Strait of Dover',
      'Cape of Good Hope',
    ]),
  },
  {
    id: 2,
    category: 'MOST POPULOUS COUNTRIES IN THE WORLD',
    options: createOptions([
      'India',
      'China',
      'United States',
      'Indonesia',
      'Pakistan',
      'Nigeria',
      'Brazil',
      'Bangladesh',
      'Russia',
      'Mexico',
    ]),
  },
  {
    id: 3,
    category: 'ALL-TIME HIGHEST GROSSING MOVIES (WORLDWIDE)',
    options: createOptions([
      'Avatar',
      'Avengers: Endgame',
      'Avatar: The Way of Water',
      'Titanic',
      'Star Wars: The Force Awakens',
      'Avengers: Infinity War',
      'Spider-Man: No Way Home',
      'Inside Out 2',
      'Jurassic World',
      'The Lion King (2019)',
    ]),
  },
  {
    id: 4,
    category: 'LARGEST OCEANS & SEAS BY SURFACE AREA',
    options: createOptions([
      'Pacific Ocean',
      'Atlantic Ocean',
      'Indian Ocean',
      'Southern Ocean',
      'Arctic Ocean',
      'Philippine Sea',
      'Coral Sea',
      'Arabian Sea',
      'South China Sea',
      'Caribbean Sea',
    ]),
  },
  {
    id: 5,
    category: 'MOST POPULAR CLASSIC BOARD GAMES OF ALL TIME',
    options: createOptions([
      'Chess',
      'Checkers',
      'Monopoly',
      'Scrabble',
      'Clue (Cluedo)',
      'The Game of Life',
      'Battleship',
      'Risk',
      'Catan',
      'Trivial Pursuit',
    ]),
  },
  {
    id: 6,
    category: 'TALLEST MOUNTAIN PEAKS ABOVE SEA LEVEL',
    options: createOptions([
      'Mount Everest (8,848m)',
      'K2 (8,611m)',
      'Kangchenjunga (8,586m)',
      'Lhotse (8,516m)',
      'Makalu (8,485m)',
      'Cho Oyu (8,188m)',
      'Dhaulagiri I (8,167m)',
      'Manaslu (8,163m)',
      'Nanga Parbat (8,126m)',
      'Annapurna I (8,091m)',
    ]),
  },
  {
    id: 7,
    category: 'MOST ABUNDANT CHEMICAL ELEMENTS IN EARTH’S CRUST',
    options: createOptions([
      'Oxygen (46.1%)',
      'Silicon (28.2%)',
      'Aluminum (8.2%)',
      'Iron (5.6%)',
      'Calcium (4.1%)',
      'Sodium (2.4%)',
      'Magnesium (2.3%)',
      'Potassium (2.1%)',
      'Titanium (0.6%)',
      'Hydrogen (0.1%)',
    ]),
  },
  {
    id: 8,
    category: 'MOST VISITED INTERNATIONAL DESTINATION CITIES',
    options: createOptions([
      'Bangkok',
      'Paris',
      'London',
      'Dubai',
      'Singapore',
      'Kuala Lumpur',
      'New York City',
      'Istanbul',
      'Tokyo',
      'Rome',
    ]),
  },
  {
    id: 9,
    category: 'LONGEST RIVERS ON PLANET EARTH',
    options: createOptions([
      'Nile River',
      'Amazon River',
      'Yangtze River',
      'Mississippi-Missouri River',
      'Yenisey River',
      'Yellow River (Huang He)',
      'Ob-Irtysh River',
      'Paraná River',
      'Congo River',
      'Amur River',
    ]),
  },
  {
    id: 10,
    category: 'MOST EXPENSIVE CULINARY SPICES BY WEIGHT',
    options: createOptions([
      'Saffron',
      'Pure Vanilla',
      'Mahlab',
      'Green Cardamom',
      'Fresh Wasabi Root',
      'Pink Peppercorn',
      'Clove Buds',
      'True Ceylon Cinnamon',
      'Star Anise',
      'Black Cumin',
    ]),
  },
  {
    id: 11,
    category: 'FASTEST RECORDED LAND ANIMALS (TOP SPRINT SPEED)',
    options: createOptions([
      'Cheetah (70 mph)',
      'Pronghorn Antelope (55 mph)',
      'Springbok (55 mph)',
      'Quarter Horse (55 mph)',
      'Blue Wildebeest (50 mph)',
      'Lion (50 mph)',
      'Blackbuck (50 mph)',
      'Hare (45 mph)',
      'Greyhound (45 mph)',
      'African Wild Dog (44 mph)',
    ]),
  },
  {
    id: 12,
    category: 'BEST-SELLING INDIVIDUAL FICTION BOOK AUTHORS',
    options: createOptions([
      'William Shakespeare',
      'Agatha Christie',
      'Barbara Cartland',
      'Danielle Steel',
      'Harold Robbins',
      'Georges Simenon',
      'Enid Blyton',
      'J. K. Rowling',
      'Sidney Sheldon',
      'Eiichiro Oda',
    ]),
  },
  {
    id: 13,
    category: 'ALL-TIME MOST STREAMED ARTISTS ON SPOTIFY',
    options: createOptions([
      'Drake',
      'Taylor Swift',
      'Bad Bunny',
      'The Weeknd',
      'Justin Bieber',
      'Ed Sheeran',
      'Ariana Grande',
      'Eminem',
      'Kanye West',
      'Post Malone',
    ]),
  },
  {
    id: 14,
    category: 'HEAVIEST ANIMAL SPECIES ON EARTH',
    options: createOptions([
      'Blue Whale',
      'Fin Whale',
      'North Pacific Right Whale',
      'Bowhead Whale',
      'Sperm Whale',
      'Humpback Whale',
      'Gray Whale',
      'African Bush Elephant',
      'Asian Elephant',
      'White Rhinoceros',
    ]),
  },
  {
    id: 15,
    category: 'MOST POPULAR ICE CREAM FLAVORS WORLDWIDE',
    options: createOptions([
      'Vanilla',
      'Chocolate',
      'Cookies & Cream',
      'Mint Chocolate Chip',
      'Strawberry',
      'Butter Pecan',
      'Chocolate Chip Cookie Dough',
      'Salted Caramel',
      'Coffee',
      'Rocky Road',
    ]),
  },
  {
    id: 16,
    category: 'ALL-TIME SUMMER OLYMPIC GOLD MEDAL NATIONS',
    options: createOptions([
      'United States',
      'Soviet Union',
      'Great Britain',
      'China',
      'France',
      'Italy',
      'Germany',
      'Hungary',
      'Japan',
      'Australia',
    ]),
  },
  {
    id: 17,
    category: 'LARGEST DESERTS ON EARTH (BY TOTAL SURFACE AREA)',
    options: createOptions([
      'Antarctic Polar Desert',
      'Arctic Polar Desert',
      'Sahara Desert',
      'Arabian Desert',
      'Gobi Desert',
      'Kalahari Desert',
      'Great Victoria Desert',
      'Syrian Desert',
      'Great Basin Desert',
      'Chihuahuan Desert',
    ]),
  },
  {
    id: 18,
    category: 'WORLD’S MOST VALUABLE COMPANIES BY MARKET CAP',
    options: createOptions([
      'Apple',
      'Microsoft',
      'NVIDIA',
      'Alphabet (Google)',
      'Amazon',
      'Saudi Aramco',
      'Meta Platforms',
      'Berkshire Hathaway',
      'Taiwan Semiconductor (TSMC)',
      'Tesla',
    ]),
  },
  {
    id: 19,
    category: 'SOLAR SYSTEM CELESTIAL BODIES BY MASS (EXCLUDING SUN)',
    options: createOptions([
      'Jupiter',
      'Saturn',
      'Neptune',
      'Uranus',
      'Earth',
      'Venus',
      'Mars',
      'Mercury',
      'Ganymede',
      'Titan',
    ]),
  },
  {
    id: 20,
    category: 'MOST POPULAR ESPRESSO-BASED CAFE DRINKS',
    options: createOptions([
      'Espresso',
      'Cappuccino',
      'Caffè Latte',
      'Americano',
      'Flat White',
      'Caffè Mocha',
      'Macchiato',
      'Cold Brew Coffee',
      'Iced Latte',
      'Cortado',
    ]),
  },
  {
    id: 21,
    category: 'MOST WATCHED TELEVISION SERIES FINALES IN US HISTORY',
    options: createOptions([
      'M*A*S*H (105.9 Million)',
      'Cheers (80.4 Million)',
      'The Fugitive (78.0 Million)',
      'Seinfeld (76.3 Million)',
      'Friends (52.5 Million)',
      'Magnum, P.I. (50.7 Million)',
      'The Cosby Show (44.4 Million)',
      'All in the Family (40.2 Million)',
      'Family Ties (36.3 Million)',
      'Home Improvement (35.5 Million)',
    ]),
  },
  {
    id: 22,
    category: 'TALLEST ARCHITECTURAL BUILDINGS ON EARTH',
    options: createOptions([
      'Burj Khalifa (Dubai, 828m)',
      'Merdeka 118 (Kuala Lumpur, 678m)',
      'Shanghai Tower (Shanghai, 632m)',
      'Abraj Al-Bait Clock Tower (Mecca, 601m)',
      'Ping An Finance Centre (Shenzhen, 599m)',
      'Lotte World Tower (Seoul, 555m)',
      'One World Trade Center (NYC, 541m)',
      'Guangzhou CTF Finance Centre (530m)',
      'Tianjin CTF Finance Centre (530m)',
      'CITIC Tower (Beijing, 528m)',
    ]),
  },
  {
    id: 23,
    category: 'LARGEST SOCIAL MEDIA PLATFORMS BY MONTHLY USERS',
    options: createOptions([
      'Facebook (3.05B)',
      'YouTube (2.50B)',
      'WhatsApp (2.00B)',
      'Instagram (2.00B)',
      'TikTok (1.60B)',
      'WeChat (1.34B)',
      'Telegram (900M)',
      'Snapchat (800M)',
      'Reddit (750M)',
      'X (Twitter, 600M)',
    ]),
  },
  {
    id: 24,
    category: 'MOST POPULAR DOG BREEDS (AKC REGISTRATIONS)',
    options: createOptions([
      'French Bulldog',
      'Labrador Retriever',
      'Golden Retriever',
      'German Shepherd',
      'Poodle',
      'Dachshund',
      'Bulldog',
      'Beagle',
      'Rottweiler',
      'German Shorthaired Pointer',
    ]),
  },
  {
    id: 25,
    category: 'MOST ABUNDANT GASES IN EARTH’S ATMOSPHERE',
    options: createOptions([
      'Nitrogen (78.08%)',
      'Oxygen (20.95%)',
      'Argon (0.93%)',
      'Carbon Dioxide (0.04%)',
      'Neon (18.18 ppm)',
      'Helium (5.24 ppm)',
      'Methane (1.91 ppm)',
      'Krypton (1.14 ppm)',
      'Hydrogen (0.55 ppm)',
      'Xenon (0.09 ppm)',
    ]),
  },
  {
    id: 26,
    category: 'MOST POPULAR MUSICAL INSTRUMENTS WORLDWIDE',
    options: createOptions([
      'Piano / Digital Keyboard',
      'Acoustic Guitar',
      'Electric Guitar',
      'Violin',
      'Drum Kit',
      'Flute',
      'Saxophone',
      'Clarinet',
      'Trumpet',
      'Cello',
    ]),
  },
  {
    id: 27,
    category: 'BEST-SELLING VIDEO GAME FRANCHISES IN HISTORY',
    options: createOptions([
      'Mario (870M+ copies)',
      'Tetris (520M+ copies)',
      'Pokémon (480M+ copies)',
      'Grand Theft Auto (430M+ copies)',
      'Call of Duty (425M+ copies)',
      'FIFA / EA Sports FC (330M+ copies)',
      'Minecraft (300M+ copies)',
      'Lego Video Games (200M+ copies)',
      'The Sims (200M+ copies)',
      'Final Fantasy (195M+ copies)',
    ]),
  },
  {
    id: 28,
    category: 'MOST HARVESTED VEGETABLES GLOBALLY (BY TONNAGE)',
    options: createOptions([
      'Tomato (189M tonnes)',
      'Onion (106M tonnes)',
      'Cucumber (93M tonnes)',
      'Cabbage (72M tonnes)',
      'Eggplant (59M tonnes)',
      'Carrot (41M tonnes)',
      'Sweet Potato (35M tonnes)',
      'Bell Pepper (36M tonnes)',
      'Garlic (28M tonnes)',
      'Spinach (32M tonnes)',
    ]),
  },
  {
    id: 29,
    category: 'MOST TRADED CURRENCIES IN GLOBAL FOREX MARKETS',
    options: createOptions([
      'United States Dollar (USD)',
      'Euro (EUR)',
      'Japanese Yen (JPY)',
      'Pound Sterling (GBP)',
      'Australian Dollar (AUD)',
      'Canadian Dollar (CAD)',
      'Swiss Franc (CHF)',
      'Chinese Renminbi (CNY)',
      'Hong Kong Dollar (HKD)',
      'New Zealand Dollar (NZD)',
    ]),
  },
  {
    id: 30,
    category: 'MOST VISITED ART MUSEUMS IN THE WORLD',
    options: createOptions([
      'Musée du Louvre (Paris)',
      'Vatican Museums (Vatican City)',
      'British Museum (London)',
      'Metropolitan Museum of Art (NYC)',
      'Tate Modern (London)',
      'National Museum of Korea (Seoul)',
      'Musée d’Orsay (Paris)',
      'National Gallery of Art (Washington)',
      'Prado Museum (Madrid)',
      'Hermitage Museum (St. Petersburg)',
    ]),
  },
];
